env:
  browser: true
  es2021: true
  node: true
extends:
  - standard
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
parserOptions:
  ecmaVersion: latest
  parser: "@typescript-eslint/parser"
  sourceType: module
  project: ./tsconfig.json
plugins:
  - "@typescript-eslint"
rules: {}
